import { useState } from 'react';
import { BrainCircuit, FolderOpen } from 'lucide-react';

export function SetupScreen({ onDone }: { onDone: () => void }) {
  const [root, setRoot] = useState(''); const [brain, setBrain] = useState(true); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  async function save() { setError(''); const r = await fetch('http://127.0.0.1:3030/setup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ projectsRoot: root, createBrain: brain }) }); const d = await r.json(); if (!r.ok) return setError(d.error || 'Setup failed.'); setDone(true); }
  if (done) return <div className="min-h-screen grid place-items-center bg-[#101413] p-6 text-white"><div className="max-w-md rounded-lg border border-[#29332f] bg-[#171d1b] p-6"><BrainCircuit className="h-8 w-8 text-[#d8ff5e]"/><h1 className="mt-4 text-2xl font-semibold">Setup saved</h1><p className="mt-2 text-sm text-[#91a19a]">Restart Jarvis once. Your projects root and shared Obsidian Brain will then be active for every CLI.</p></div></div>;
  return <div className="min-h-screen grid place-items-center bg-[#101413] p-6 text-white"><div className="w-full max-w-md rounded-lg border border-[#29332f] bg-[#171d1b] p-6"><BrainCircuit className="h-8 w-8 text-[#d8ff5e]"/><p className="mt-4 font-mono text-[10px] uppercase tracking-[.2em] text-[#d8ff5e]">First-run setup</p><h1 className="mt-1 text-2xl font-semibold">Tell Jarvis where work lives.</h1><p className="mt-2 text-sm text-[#91a19a]">This folder contains the projects every agent can coordinate on. It stays local to this machine.</p><label className="mt-5 block text-sm">Projects folder</label><div className="mt-2 flex gap-2"><FolderOpen className="mt-2 h-4 w-4 text-[#91a19a]"/><input value={root} onChange={(e) => setRoot(e.target.value)} placeholder="C:\\Users\\you\\projects" className="flex-1 border-b border-[#29332f] bg-transparent py-2 outline-none focus:border-[#d8ff5e]"/></div><label className="mt-5 flex gap-2 text-sm"><input type="checkbox" checked={brain} onChange={(e) => setBrain(e.target.checked)}/> Create one shared Obsidian Brain for all projects</label>{error && <p className="mt-3 text-sm text-[#ff8b7d]">{error}</p>}<button onClick={save} className="mt-6 w-full rounded-md bg-[#d8ff5e] py-2 text-sm font-semibold text-[#101413]">Save and restart Jarvis</button></div></div>;
}
